// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Person.proto
// Protobuf Java Version: 4.27.1

package com.sgp.domain;

public final class AddressBookProto {
  private AddressBookProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      AddressBookProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sgp_domain_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sgp_domain_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sgp_domain_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sgp_domain_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sgp_domain_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sgp_domain_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\016com.sgp.domain\"\257\002\n\006Perso" +
      "n\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001" +
      "(\t\0222\n\006phones\030\004 \003(\0132\".com.sgp.domain.Pers" +
      "on.PhoneNumber\032^\n\013PhoneNumber\022\016\n\006number\030" +
      "\001 \001(\t\022?\n\004type\030\002 \001(\0162 .com.sgp.domain.Per" +
      "son.PhoneType:\017PHONE_TYPE_HOME\"h\n\tPhoneT" +
      "ype\022\032\n\026PHONE_TYPE_UNSPECIFIED\020\000\022\025\n\021PHONE" +
      "_TYPE_MOBILE\020\001\022\023\n\017PHONE_TYPE_HOME\020\002\022\023\n\017P" +
      "HONE_TYPE_WORK\020\003\"5\n\013AddressBook\022&\n\006peopl" +
      "e\030\001 \003(\0132\026.com.sgp.domain.PersonB$\n\016com.s" +
      "gp.domainB\020AddressBookProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sgp_domain_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sgp_domain_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sgp_domain_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_com_sgp_domain_Person_PhoneNumber_descriptor =
      internal_static_com_sgp_domain_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_sgp_domain_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sgp_domain_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_com_sgp_domain_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sgp_domain_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_sgp_domain_AddressBook_descriptor,
        new java.lang.String[] { "People", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
